### ISSUE TITLE
error reading config file: read /etc/kowl/config.yaml: is a directory when starting local with docker-compose

### ISSUE THREAD

**Issue by mcclone2001** [cloudhut/kowl#106]
Running zookeeper an kafka like this in a terminal
```
docker-compose up zoo1 kafka1
```
an running kowl like this in another terminal
```
docker-compose up kowl
```
using this docker-compose.yml in docs/local 
```
version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    restart: on-failure
    hostname: kowl
    volumes:
    - ./config.yaml:/etc/kowl/config.yaml
    ports:
    - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka1
```

output
```
Attaching to local_kowl_1
kowl_1    | {"level":"info","msg":"started Kowl","version":"v1.1.0","built":"2020-08-06T20:16:16Z","git_sha":"c1f037f3175897f9ca7213b5588d12e188b88c9b"}
kowl_1    | {"level":"fatal","msg":"failed to load yaml config","error":"error reading config file: read /etc/kowl/config.yaml: is a directory"}
```

looks like a problem with volumes?

Ubuntu with wsl on Windows 10
docker-compose version 1.25.4, build unknown
Docker version 19.03.9, build 9d988398e7
