### ISSUE TITLE
Impossible to enable schemaRegistry using helm chart

### ISSUE THREAD

**Issue by dicolasi** [cloudhut/kowl#151]
I am trying to enable schemaRegistry as per documentation (https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml). However, got the following error: 

```
 {"level":"info","msg":"started Kowl","version":"v1.1.0","built":"2020-08-06T20:16:16Z","git_sha":"c1f037f3175897f9ca7213b5588d12e188b88c9b"}                                                                                                                                 │
│ {"level":"fatal","msg":"failed to load yaml config","error":"error parsing config file: yaml: unmarshal errors:\n  line 6: field schemaRegistry not found in type kafka.Config"}                                                                                             │
│ stream closed
```

Here the configMap content: 

```
  config.yaml: |
    kafka:
      brokers:
      - kakfa-stage-kafka-bootstrap.strimzi.svc:9092
      tls:
       enabled: false
      schemaRegistry:
       enabled: false
```
