### ISSUE TITLE
Can't see multiple brokers

### ISSUE THREAD

**Issue by stavalfi** [cloudhut/kowl#160]
config.yaml:
```
kafka:
  brokers:
    - kafka_dcomp:9092
    - <some-ip-to-other-kafka>:9092
```

### **NOTE: If I remove "kafka_dcomp:9092", I can see the second kafka in kowl with no problems!!!**

Kowl logs:
```
{"level":"info","msg":"started Kowl","version":"v1.2.2","built":"2020-11-23T15:49:59Z","git_sha":"284eb140e520ee647f8801992c54e7ad05b3c0c3"}
{"level":"info","ts":"2021-01-05T13:33:29.332Z","msg":"connecting to Kafka cluster"}
{"level":"info","ts":"2021-01-05T13:33:29.350Z","msg":"connected to at least one Kafka broker"}
{"level":"info","ts":"2021-01-05T13:33:29.351Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
{"level":"info","ts":"2021-01-05T13:33:32.354Z","msg":"connection to all brokers healthy","brokers":1}
```

> "brokers":1.   --->> why? 

docker-compose:
```
version: '3'

services:
  kafka-ui-2:
    image: quay.io/cloudhut/kowl:v1.2.2
    container_name: kafka-ui-2
    restart: on-failure
    hostname: kowl
    volumes:
    - ./config.yaml:/etc/kowl/config.yaml
    ports:
    - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka_dcomp
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-test
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka_dcomp:
    image: 'bitnami/kafka:latest'
    container_name: kafka-test
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_dcomp:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

```

![image](https://user-images.githubusercontent.com/12954665/103653331-0fcc2a00-4f6d-11eb-97b0-cd581a4defab.png)

how can I see debug logs?

are multiple kafka supported?
