### ISSUE TITLE
Feature Request: Pre-configured topic search filters

### ISSUE THREAD

**Issue by clarknova9** [cloudhut/kowl#167]
The topic search filter is a fantastic feature, but it must be created by each user and is only stored in the browser client. 

It would be beneficial if Kowl could include support for pre-configured search filters per topic available to all users.

Here are my initial thoughts on what the config block could look like.

```
searchFilters:
  filterName1: 
    topic: topic-name   ## name of the topic
    filter: "if (key == 'example') return true"  ## filter function
   enabled: true  ## enabled or disabled by default
```
