### ISSUE TITLE
Error using SASL/SCRAM 

### ISSUE THREAD

**Issue by acepsaepudin** [cloudhut/kowl#173]
**Context:**
> I want to connect to MSK ( Kafka managed by AWS ) and that is using SASL/SCRAM as authentication method.

**Machine information**
- Kowl version: tag: v1.2.2
- config.yml
```
kafka:
  brokers:
    - broker1:9096
    - broker2:9096
    - broker3:9096

  clientId: kowl
  sasl:
    enabled: true
    useHandshake: true
    username: "username"
    password: "password"
    mechanism: "SCRAM-SHA-512"

logger:
  level: debug
```
- error log
```
{"level":"info","msg":"started Kowl","version":"1.2.2","built":"2021-02-15T08:47:44Z","git_sha":"284eb140e520ee647f8801992c54e7ad05b3c0c3"}
{"level":"info","ts":"2021-02-15T08:52:33.219Z","msg":"connecting to Kafka cluster"}
{"level":"debug","ts":"2021-02-15T08:52:33.219Z","msg":"Initializing new client","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.219Z","msg":"client/metadata fetching metadata for all topics from broker broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.251Z","msg":"Failed to read SASL handshake header : unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.251Z","msg":"Closed connection to broker broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.252Z","msg":"client/metadata got error from broker -1 while fetching metadata: unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.252Z","msg":"client/metadata fetching metadata for all topics from broker broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.258Z","msg":"Failed to read SASL handshake header : unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.259Z","msg":"Closed connection to broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.259Z","msg":"client/metadata got error from broker -1 while fetching metadata: unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.259Z","msg":"client/metadata fetching metadata for all topics from broker broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.266Z","msg":"Failed to read SASL handshake header : unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.266Z","msg":"Closed connection to broker broker:9096","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.266Z","msg":"client/metadata got error from broker -1 while fetching metadata: unexpected EOF","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.266Z","msg":"client/metadata no available broker to send metadata request to","source":"sarama"}
{"level":"debug","ts":"2021-02-15T08:52:33.266Z","msg":"client/brokers resurrecting 3 dead seed brokers","source":"sarama"}
```

*Pardon me if my question is not clear enough.

**Comment by weeco** [comment]
@acepsaepudin Hey, could you try the same with a version from master? We replaced the Kafka Client with a new one. If the issue persists there, I'm pretty convinced it's not an issue with the Kafka client. But maybe we get also more insights from these logs. Please keep in mind that the version on master has some minor unfixed issues.

**Comment by acepsaepudin** [comment]
@weeco 

first, I got this error:
```
{"level":"fatal","msg":"failed to load yaml config","error":"error parsing config file: yaml: unmarshal errors:\n  line 10: field useHandshake not found in type kafka.SASLConfig"}
```
config in master: https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml

I remove the `useHandshake` and got this error:
```
{"level":"info","ts":"2021-02-15T09:33:17.032Z","msg":"started Kowl","version":"1.2.2","git_sha":"3aba6a70bf2353d75e79069a28078eb421f0254f","built":"2021-02-15T09:18:18Z"}
{"level":"info","ts":"2021-02-15T09:33:17.032Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"debug","ts":"2021-02-15T09:33:17.032Z","msg":"opening connection to broker","source":"kafka_client","addr":"brokercom:9096","id":-2147483648}
{"level":"debug","ts":"2021-02-15T09:33:17.041Z","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"broker","dial_duration":0.008552525}
{"level":"debug","ts":"2021-02-15T09:33:17.041Z","msg":"connection opened to broker","source":"kafka_client","addr":"broker:9096","id":-2147483648}
{"level":"debug","ts":"2021-02-15T09:33:17.041Z","msg":"issuing api versions request","source":"kafka_client","version":3}
{"level":"error","ts":"2021-02-15T09:33:17.046Z","msg":"unable to request api versions","source":"kafka_client","err":"invalid large response size 352518912 > limit 104857600"}
{"level":"debug","ts":"2021-02-15T09:33:17.046Z","msg":"connection initialization failed","source":"kafka_client","addr":"broker:9096","id":-2147483648,"err":"invalid large response size 352518912 > limit 104857600"}
{"level":"debug","ts":"2021-02-15T09:33:17.046Z","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"broker"}
{"level":"fatal","ts":"2021-02-15T09:33:17.046Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: invalid large response size 352518912 > limit 104857600"}
```

**Comment by weeco** [comment]
@acepsaepudin Thanks for pointing this out, useHandshake should be removed indeed from the config.

I just took another look at your config. My assumption is that the Amazon MSK clusters use TLS (using trusted certs?). Can you enable TLS in your config and retry?

**Comment by acepsaepudin** [comment]
@weeco 
> I just took another look at your config. My assumption is that the Amazon MSK clusters use TLS (using trusted certs?). Can you enable TLS in your config and retry?

nope, in MSK we only enabling the SASL/SCRAM. TLS/SSL already tried also but not working, only MSK with `plaintext` is working.

**Comment by weeco** [comment]
I'm not familiar with Amazon's MSK , but using authentication without TLS is insecure as the credentials are unencrypted and everyone on the network can read and use them. The AWS documentation makes it sound like TLS encryption is required if you want to use authentication - which would make sense for me:

> To use client authentication, you need an ACM Private CA. For information about private CAs, see Creating and Managing a Private CA.

Reference: https://docs.aws.amazon.com/msk/latest/developerguide/msk-authentication.html

In case you use a custom CA you need to provide the custom CA certificate to Kowl as well. Other than that I can't be of more help I think. We pass these connection options straight to the Kafka clients.

**Comment by acepsaepudin** [comment]
> Reference: https://docs.aws.amazon.com/msk/latest/developerguide/msk-authentication.html

yes correct, but it's for TLS as authentication and we are using this options: [https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html](https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html)


> In case you use a custom CA you need to provide the custom CA certificate to Kowl as well. Other than that I can't be of more help I think. We pass these connection options straight to the Kafka clients.

in other hand, is it possible if we disable ssl certificate verification in kowl ? something like this:
`enable.ssl.certificate.verification = False`

**Comment by weeco** [comment]
Yes the respective option in Kowl is here: https://github.com/cloudhut/kowl/blob/43edbf42788c56b9711c524d712269fa75168b31/docs/config/kowl.yaml#L30

**Comment by acepsaepudin** [comment]
is it under `tls` right ? and we need to provide the tls certificate ? if yes, I think it's not what I want for now.

I already check my client application and it's using `SASL/SCRAM`, and we need to enable this: `enable.ssl.certificate.verification = False` ( because of limitation from MSK with `SASL/SCRAM` for now)

**Comment by weeco** [comment]
If you are unsure whether TLS is required at all or not, try to add the below config

```
kafka:
  tls:
    enabled: true
    insecureSkipTlsVerify: true
```

**Comment by acepsaepudin** [comment]
```
{"level":"info","ts":"2021-02-15T10:28:37.721Z","msg":"successfully connected to kafka cluster","advertised_broker_count":3,"topic_count":18,"controller_id":3,"kafka_version":"v2.6"}
{"level":"debug","ts":"2021-02-15T10:28:37.721Z","msg":"using compression for all http routes","level":4}
{"level":"info","ts":"2021-02-15T10:28:37.723Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
```

wow amazing! 👍 thanks you for your help @weeco 🙏

**Comment by GreenGuy09** [comment]
Tweaking the tls verify to false also worked for Azure Event Hubs. here's a sample docker-compose. hope this helps a random stranger one day!

```
version: "3.9"
services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    environment:
      KAFKA_BROKERS: NAMESPACENAME.servicebus.windows.net:9093 #INSERT NAMESPACE HERE (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas)
      KAFKA_CLIENTID: kowl
      KAFKA_SASL_ENABLED: true
      KAFKA_SASL_USERNAME: $$ConnectionString # DON'T TOUCH THIS!!!!
      KAFKA_SASL_PASSWORD: Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXXXXXXXXX #INSERT FULL CONNECTION STRING HERE (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas)
      KAFKA_SASL_MECHANISM: PLAIN
      KAFKA_TLS_ENABLED: true
      KAFKA_TLS_INSECURESKIPTLSVERIFY: true
      # LOGGER_LEVEL: debug      
    ports:
      - "8080:8080"
```
