### ISSUE TITLE
How to enable TSL?

### ISSUE THREAD

**Issue by AskMeAgain** [cloudhut/kowl#182]
Hi,

this is my config file:

```
kafka:
  tls:
    enabled: true
    caFilepath: /etc/kowl/secrets/CARoot.pem
    certFilepath: /etc/kowl/secrets/kowl.pem
    insecureSkipTlsVerify: true
  brokers:
    - kafka:9092
```

i found this issue here: https://github.com/cloudhut/kowl/issues/104 -> the openssl verification works on my side too:

```
openssl verify -verbose -CAfile CARoot.pem kowl.pem
kowl.pem: OK
```

I get no helpful error message by kowl:

```
{"level":"info","msg":"started Kowl","version":"v1.2.2","built":"2020-11-23T15:49:59Z","git_sha":"284eb140e520ee647f8801992c54e7ad05b3c0c3"}
{"level":"info","ts":"2021-02-24T13:49:24.604Z","msg":"connecting to Kafka cluster"}
{"level":"fatal","ts":"2021-02-24T13:49:25.479Z","msg":"failed to create kafka service","error":"failed to create kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
```

Yes the Broker is reachable...
