### ISSUE TITLE
Support Azure Event Hub

### ISSUE THREAD

**Issue by jackiesphan1996** [cloudhut/kowl#229]

**Comment by weeco** [comment]
As far as I understand you can use Azure's Event Hub for Apache Kafka which is fully API compatible and therefore should already work.

We don't intend to make Kowl compatible with other backends that don't comply with the Kafka protocol.

**Comment by GreenGuy09** [comment]
@jackiesphan1996 This configuration worked for my docker-compose and event hubs:

```
version: "3.9"
services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    environment:
      KAFKA_BROKERS: NAMESPACENAME.servicebus.windows.net:9093 #INSERT NAMESPACE HERE (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas)
      KAFKA_CLIENTID: kowl
      KAFKA_SASL_ENABLED: true
      KAFKA_SASL_USERNAME: $$ConnectionString # DON'T TOUCH THIS!!!!
      KAFKA_SASL_PASSWORD: Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXXXXXXXXX #INSERT FULL CONNECTION STRING HERE (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas)
      KAFKA_SASL_MECHANISM: PLAIN
      KAFKA_TLS_ENABLED: true
      KAFKA_TLS_INSECURESKIPTLSVERIFY: true
      # LOGGER_LEVEL: debug      
    ports:
```
