### ISSUE TITLE
Docker-compose.yml kowl v1.4.0 fails to connect on startup while v1.3.0 works

### ISSUE THREAD

**Issue by saberder** [cloudhut/kowl#238]
`docker-compose up -d` produces the gui error: "NetworkError when attempting to fetch resource." and the retry button doesn't work. However, running each service **sequentially** works.

This is not a problem with the kowl v1.3.0 docker image

docker-compose.yml:
```
#version: '3'
services:
  redpanda1:
    image: vectorized/redpanda:v21.7.6
    container_name: redpanda1
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda1:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    container_name: kowl
    environment:
      - KAFKA_BROKERS=redpanda1:29092
    ports:
      - 8080:8080
    depends_on:
      - "redpanda1"
```
