### ISSUE TITLE
Protobuf Imports not working

### ISSUE THREAD

**Issue by CEikermann** [cloudhut/kowl#265]
Follow up from https://github.com/cloudhut/kowl/pull/254

Docker Desktop 4.0.0 @ MacOS 11.4
```
{"level":"warn","ts":"2021-09-08T14:57:48.032Z","msg":"failed to parse proto file to descriptor","file":"/test_a.proto","line":5,"error":"/test_a.proto:5:8: test_b.proto: file does not exist"}
{"level":"fatal","ts":"2021-09-08T14:57:48.032Z","msg":"failed to start kafka service","error":"failed to create proto registry: failed to compile proto files to descriptors: failed to parse proto files to descriptors: parse failed: invalid proto source"}
```

Way to Reproduce

/tmp/protobuf/test_a.proto
```syntax = "proto3";

package test.a.protobuf;

import "test_b.proto";

message TestA {
  string test = 1;
  test.b.protobuf.TestB testB = 2;
}
```

/tmp/protobuf/test_b.proto
```syntax = "proto3";

package test.b.protobuf;

message TestB {
  string test = 1;
}
```

/tmp/kowl-config.yml
```
kafka:
  brokers:
    - kafka:9092
  protobuf:
    enabled: true
    mappings:
      - topicName: testtopic
        valueProtoType: test.a.protobuf.TestA
    fileSystem:
      enabled: true
      refreshInterval: 5m
      paths:
        - /etc/protos
```

docker-compose.yml
```
  kafka-ui:
    image: quay.io/cloudhut/kowl:master-11afdfa
    restart: unless-stopped
    volumes:
      - /tmp/kowl-config.yml:/etc/kowl/config.yml
      - /tmp/protobuf/:/etc/protos/
    ports:
      - 8080:8080
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yml
    depends_on:
      - kafka
    networks:
      - main
  ```
