### ISSUE TITLE
Consumption limited to one Kowl consumer pod

### ISSUE THREAD

**Issue by OuesFa** [cloudhut/kowl#287]
Hello 👋 
When trying to find an event within a topic containing 17Gb of data, I was expecting that Kowl create as much consumers as needed to go fast when reaching the hpa cpu threshold (limited by hpa max replicas & number of topic partitions)   

However, what I can see is that the cpu is at its limit on one pod and others are idle 
```
$ kubectl top pod --containers  |grep -i kowl
kowl-6497f6749f-ctzz8                                             istio-proxy                       5m           49Mi
kowl-6497f6749f-ctzz8                                             kowl                              1m           20Mi
kowl-6497f6749f-hznt4                                             istio-proxy                       6m           49Mi
kowl-6497f6749f-hznt4                                             kowl                              1m           19Mi
kowl-6497f6749f-ld24k                                             istio-proxy                       17m          54Mi
kowl-6497f6749f-ld24k                                             kowl                              994m         138Mi 
```
Here are the relevant Kowl confs
```
[...]
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 128Mi
[...]
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 7
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
[...]
```
Also, it's not creating other pods even though the cpu is higher than the threshold.

Is it possible to make it search for the records faster? Thanks 🙏 

EDIT:
Besides, after a while of fetching data (~5.14 GB), kowl just stops processing even when there is no result returned.
What could explain this behaviour knowing that the topic contains more data according to Kowl (see the image)?
<img width="1512" alt="Capture d’écran 2021-12-03 à 20 18 21" src="https://user-images.githubusercontent.com/10348298/144660460-828adbb5-c4fd-4158-88bd-c2072d5778e5.png">
