### ISSUE TITLE
disable delete buttons

### ISSUE THREAD

**Issue by papillon88** [cloudhut/kowl#289]
Hi,

Is there any way I can disable the "delete" buttons in the Kowl UI at the places shown below (in the topics list and the messages list within a topic) ? We were planning to use KOWL as a replacement for Kafka TopicsUI only if we can disable those delete buttons. 

![image](https://user-images.githubusercontent.com/11804111/145468863-43784b7c-8e4f-44d0-b571-78771b00ad18.png)

![Untitled2](https://user-images.githubusercontent.com/11804111/145469267-ada82225-4d19-4919-920a-a2c1aab18f5d.png)

**Comment by weeco** [comment]
Hi @papillon88 ,
for permissions stuff we recommend using Kowl Business which is currently also free to use. You can configure the permissions very granularly there. We don't want to introduce two different permission systems in Kowl Business and Kowl as of now.

**Comment by papillon88** [comment]
we use okta and sso for apps on our K8s. how many users/individual SSOs can fit in one seat ? for Kowl business I see 2 free seats - so means 2 users and for more users its 12$ per user ?

The link I click on doesnt take me anywhere -> circles me back to [cloudhut.dev
](https://cloudhut.dev/)
![image](https://user-images.githubusercontent.com/11804111/145652233-a5d25909-556e-46b2-b6b2-f3a0df8df254.png)

**Comment by weeco** [comment]
Right each user is one seat. Just send me your license Id from the license panel to info@cloudhut.dev and let me know how many seats you'd like to have. I can bump them then :)

**Comment by papillon88** [comment]
thanks. For now Im using a github account for login. Using helm. Below is my values.yaml 

```
replicaCount: 1

image:
  registry: xxxxxxxxxxxxxxxxxxxxx
  repository: cloudhut/kowl-business
  pullPolicy: Always
  tag: "v1.5.1"

nameOverride: kowl-business

imagePullSecrets:
  - name: xxxxxxxxxxxxxxxxxxxxx

serviceAccount:
  create: true

podSecurityContext:
  runAsUser: 99
  fsGroup: 99

securityContext:
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: xxxxxxxxxxxxxxxxxxxxx
  hosts:
    - host: xxxxxxxxxxxxxxxxxxxxx
      paths:
        - path: /kafka/kowl-ui
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 1m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 600Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 90

nodeSelector:
  xxxxxxxxxxxxxxxxxxxxx

tolerations:
  - key: "xxxxxxxxxxxxxxxxxxxxx"
    operator: "Exists"


secret:
  existingSecret: kowl-business

kowl:
  config:
    kafka:
      brokers:
        - xxxxxxxxxxxxxxxxxxxxx:9092
        - xxxxxxxxxxxxxxxxxxxxx:9092
    login:
      github:
        enabled: true
        clientId: xxxxxxxxxxxxxxxxxxxxx
    business:
      rolesFilepath: /etc/kowl/configs/roles.yaml # YAML file is always mounted under that path
      roleBindingsFilepath: /etc/kowl/configs/role-bindings.yaml # YAML file is always mounted under that path
      auditLog:
        enabled: true
    server:
      basePath: /kafka/kowl-ui
      setBasePathFromXForwardedPrefix: false
      stripPrefix: true

  roles:
    - name: developer
      permissions:
        - resource: consumerGroups
          includes: [ "/.*/" ]
          allowedActions: [ "admin" ]
        - resource: topics
          includes: [ "/.*/" ]
          excludes: [ "battle-logs" ]
          allowedActions: [ "viewer" ]
        - resource: cluster
          allowedActions: [ "viewAcl" ]
        - resource: topics
          includes: [ "battle-logs" ]
          allowedActions: [ "seeTopic", "viewPartitions", "viewConfig" ]

  roleBindings:
    - metadata:
        name: Developers
      subjects:
        - kind: user
          provider: GitHub
          name: xxxxxxxxxxxxxxxxxxxxx
      roleName: developer
```

And below is my secret file -

```
apiVersion: v1
kind: Secret
metadata:
  name: kowl-business
  namespace: monitoring
type: Opaque
stringData:
  # Kafka
  kafka-sasl-password: ""
  kafka-tls-ca: ""
  kafka-tls-cert: ""
  kafka-tls-key: ""
  kafka-tls-passphrase: ""

  # CloudHut
  cloudhut-license-token: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"

  # OAuth Login
  login-jwt-secret: ""
  login-google-oauth-client-secret: ""
  login-google-groups-service-account.json: ""
  login-github-oauth-client-secret: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
  login-github-personal-access-token: ""
  login-okta-client-secret: ""
  login-okta-directory-api-token: ""
```
I have a below queries

1. The pod keeps crashing. Logs say -
{"level":"fatal","msg":"failed to validate config","error":"failed to validate login config: you must set a secret key for signing the session JWTs"}
Not sure what Im missing here. I'm using Github login and followed the guides here -
https://cloudhut.dev/docs/provider-setup/github
https://github.com/cloudhut/charts/tree/master/examples

2. is the placement for server.basePath in values.yaml correct ?

**Comment by weeco** [comment]
Hey @papillon88 ,
after the login was successful a user session will be created. We use JWT for the session and it will be transferred to the frontend. In short: Please just use a random password / secret string as `login-jwt-secret`.

Also have a look at the role you have configured there. While that would work it was just an example to demonstrate what it would look like. You will probably not have a Kafka topic called `battle-logs` etc.

server.basePath is set at the correct level 👍

**Comment by papillon88** [comment]
Thanks @weeco provided the login-jwt-secret. the pods works correctly but I hit another roadblock -

below is my ingress config -

```
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: XXXXXXXXXXXXXXX-nginx
  hosts:
    - host: abcd.com
      paths:
        - path: /kafka/kowl-ui
          pathType: ImplementationSpecific
```

below is the basepath config - 

```
    server:
      basePath: "/kafka/kowl-ui"
      setBasePathFromXForwardedPrefix: false
      stripPrefix: true
```

below if the github Oauth app URL config (configured using https://cloudhut.dev/docs/provider-setup/github#github-oauth-provider-setup) -

```
https://abcd.com/kafka/kowl-ui/
https://abcd.com/kafka/kowl-ui/login/callbacks/github
```

the issue is upon hitting https://abcd.com/kafka/kowl-ui, Im taken to https://pb-k8s-operations.pbdevtesting.com/kafka/kowl-ui/login. After I click on github icon and it redirects me to https://abcd.com/kafka/kowl-ui/kafka/kowl-ui/login. 
No auth happens. 

Is this the correct config ? Do I need to host a separate Oauth proxy for github in my K8s cluster and have my Oauth app callback in Github point to this proxy ?

**Comment by rikimaru0345** [comment]
Do you also get wrong redirects in the free version of kowl?
I'll take a look.

**Comment by rikimaru0345** [comment]
So a few things:
- If your proxy sets `X-Forwarded-Prefix` properly, then you don't have to set `basePath` in kowls config because if kowl sees `X-Forwarded-Prefix` that will override any `basePath` setting you have anyway.
- If you are using rewrite rules in your proxy that modify incoming requests and remove that base path, then set `stripPrefix` to false otherwise kowl will (try to) remove the the prefix again from the request url.

```yaml
  basePath: "/kafka/kowl-ui"
  setBasePathFromXForwardedPrefix: true
  stripPrefix: false
```

Just to make sure:
You're using nginx; does it - in your setup - set `X-Forwarded-Prefix`?
And do you use rewrite rules (to remove the prefix before it arrives at kowl)?


In any case, if the free version of kowl works fine for you in this setup (as in, api calls the frontend sends corectly arrive at the backend), then that means it is a bug that only has to do with the login handling.
I'll investigate and let you know what I find.
