### ISSUE TITLE
Unable to define basic auth password via env

### ISSUE THREAD

**Issue by CEikermann** [cloudhut/kowl#305]
Hey,

I'm currently trying to set the password for basic auth via env variable, but it seems to not working.

kowl.yml
````
# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:9092
  protobuf:
    enabled: false # Enable it in docker-compose.yml
    mappings:
      ...............
    git:
      enabled: true
      repository:
        url: https://............git
        baseDirectory: .............
      refreshInterval: 24h
      basicAuth:
        enabled: true
        username: token
        #password: "<undefined>" # Set it via docker-compose.yml file
````

docker-compose.yml

````
  kafka-ui:
    image: quay.io/cloudhut/kowl:master-0e7d7d5
    restart: unless-stopped
    volumes:
      - ./docker/kafka-ui/config.yml:/etc/kowl/config.yml
    ports:
      - 9093:8080
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yml
    depends_on:
      - kafka
    environment:
      - KAFKA_PROTOBUF_ENABLED=true
      - KAFKA_PROTOBUF_GIT_BASICAUTH_PASSWORD="<gitlab personal access token>"
    networks:
      - main
````

The env variable KAFKA_PROTOBUF_ENABLED is recognized correctly, while KAFKA_PROTOBUF_GIT_BASICAUTH_PASSWORD not. 

Error:
````
dev-kafka-ui-1  | {"level":"fatal","ts":"2022-01-18T09:43:37.250Z","msg":"failed to start kafka service","error":"failed to start git service: failed to clone git repo: authentication required"}
````

In case I'm setting the password directly into the kowl config, everything works as expected - seems like the password will be not set via environment variable

What is the correct way to pass the basic auth password as environment variable?

**Comment by CEikermann** [comment]
Thanks @weeco - no problem at all! - Thanks for taking care on this!

**Comment by weeco** [comment]
@CEikermann I figured out that the problem is with the casing of the `basicAuth` property. Because casing with Env variables gets lost the Koanf lib does not longer merge `BASICAUTH` into the key that is called `basicAuth` within Koanf.

That's unfortunate given that I don't want to introduce a breaking change for these keys. Here's someone else who had the same issue with Koanf: https://github.com/knadh/koanf/issues/103 

I'm unsure how I want to handle it currently, but maybe you can propagate the env value to a flag which should work, e.g.: https://github.com/cloudhut/terraform-modules/blob/master/modules/kowl/deployment.tf#L58

**Comment by CEikermann** [comment]
Hey @weeco 

Thanks for the info, I was trying this approach out, but it seems it does not work as well.

docker-compose.yml
````
  kafka-ui:
    image: quay.io/cloudhut/kowl:master-0e7d7d5
    restart: unless-stopped
    volumes:
      - ./docker/kafka-ui/config.yml:/etc/kowl/config.yml
    ports:
      - 9093:8080
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yml --owl.topic-documentation.git.basic-auth.password="........."
    depends_on:
      - kafka
    networks:
      - main
`````

````
dev-kafka-ui-1  | {"level":"fatal","ts":"2022-01-20T09:07:39.156Z","msg":"failed to start kafka service","error":"failed to start git service: failed to clone git repo: authentication required"}
````

In case I'm setting the password directly in the config, it works as intended
