### ISSUE TITLE
Connection fails with tls: bad record MAC

### ISSUE THREAD

**Issue by 4integration** [cloudhut/kowl#334]
Hi,

Testing Kowl but I get this error `tls: bad record MAC`
Full output:
```
kowl_1  | {"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
kowl_1  | {"level":"info","ts":"2022-03-29T12:55:23.258Z","msg":"started Kowl","version":"master","git_sha":"c6a6f4cb15d9e58e28b13930af95b272e2eae2ca","built":"2022-02-27T09:45:11Z"}
kowl_1  | {"level":"info","ts":"2022-03-29T12:55:23.266Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.266Z","msg":"opening connection to broker","source":"kafka_client","addr":"kafka-app-test.mydomain.net:9193","broker":"seed 0"}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.314Z","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"kafka-app-test.mydomain.net","dial_duration":0.0478782}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.314Z","msg":"connection opened to broker","source":"kafka_client","addr":"kafka-app-test.mydomain.net:9193","broker":"seed 0"}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.314Z","msg":"issuing api versions request","source":"kafka_client","broker":"seed 0","version":3}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.314Z","msg":"wrote ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_written":61,"write_wait":0.0000375,"time_to_write":0.0000462,"err":null}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.347Z","msg":"read ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_read":0,"read_wait":0.0000645,"time_to_read":0.032389,"err":"local error: tls: bad record MAC"}
kowl_1  | {"level":"error","ts":"2022-03-29T12:55:23.347Z","msg":"unable to request api versions","source":"kafka_client","broker":"seed 0","err":"local error: tls: bad record MAC"}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.347Z","msg":"connection initialization failed","source":"kafka_client","addr":"kafka-app-test.mydomain.net:9193","broker":"seed 0","err":"local error: tls: bad record MAC"}
kowl_1  | {"level":"debug","ts":"2022-03-29T12:55:23.347Z","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"kafka-app-test.mydomain.net"}
kowl_1  | {"level":"fatal","ts":"2022-03-29T12:55:23.347Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: local error: tls: bad record MAC"}
```

Using this `docker-compose.yaml`
```
version: '2'

services:

  kowl:
    image: 'quay.io/cloudhut/kowl:master'
    ports:
      - '8088:8080'
    environment:
      - KAFKA_BROKERS=kafka-app-test.mydomain.net:9193
      - KAFKA_TLS_ENABLED=true
      - KAFKA_TLS_CAFILEPATH=/vdsp_test_ca.cer
      - KAFKA_TLS_KEYFILEPATH=/cert.p12
      - KAFKA_TLS_PASSPHRASE=4IfS**************6dxGj
      - KAFKA_TLS_INSECURESKIPTLSVERIFY=true
      - LOGGER_LEVEL=debug
    volumes:
      - '/c/Users/myuserid/projects/kowl/certs/vdsp_test_ca.cer:/vdsp_test_ca.cer'
      - '/c/Users/myuserid/projects/kowl/certs/cert.p12:/cert.p12'
```

Any idea why this happens?

**Comment by 4integration** [comment]
I am a dumb ass ;)
It works better if adding the certificate :)

```
version: '2'

services:
  kowl:
    image: 'quay.io/cloudhut/kowl:master'
    ports:
      - '8088:8080'
    environment:
      - KAFKA_BROKERS=kafka-app-test.mydomain.net:9193
      - KAFKA_TLS_ENABLED=true
      - KAFKA_TLS_CAFILEPATH=/vdsp_test_ca.cer
      - KAFKA_TLS_CERTFILEPATH=/cert.crt
      - KAFKA_TLS_KEYFILEPATH=/cert.key
      - KAFKA_TLS_PASSPHRASE=4IfS**************6dxGj
      - KAFKA_TLS_INSECURESKIPTLSVERIFY=true
      - LOGGER_LEVEL=debug
    volumes:
      - '/c/Users/myuserid/projects/kowl/certs/vdsp_test_ca.cer:/vdsp_test_ca.cer'
      - '/c/Users/myuserid/projects/kowl/certs/cert.crt:/cert.crt'
      - '/c/Users/myuserid/projects/kowl/certs/cert.key:/cert.key'
```
